version: "3.7"
volumes:
    logs:
        driver: local
services:
    visitor-management:
        build: .
        environment:
            docker: "true"
        ports:
            - 8080:80
        volumes:
            - ./app:/var/www/app
            - ./config:/var/www/config
            - ./logs:/var/www/logs
            - ./public:/var/www/public
            - ./src:/var/www/src
            - ./var:/var/www/var
            - ./templates:/var/www/templates
        networks:
            - visitor-management
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=navigate
            - POSTGRES_USER=lauren
            - POSTGRES_PASSWORD=goFish49!zp9
            - POSTGRES_PORT=5432
            - ENV=dev
            - LOG_TARGET=/var/www/logs/app.log
            - REDIS_HOST=localhost
            - REDIS_PORT=5530
            - VIRTUAL_HOST=api.navigate360.com
        depends_on:
            - postgres
    postgres:
        image: alpine:latest
        command:
            - sh
            - -c
            - |
                apk add putty
                apk add openssh-client
                puttygen /root/.ssh/key.ppk -O private-openssh -o /root/.ssh/id_rsa
                while true; do ssh -4 -oStrictHostKeyChecking=no -nNT -L *:5432:test-innovations-v01.cm2dbdfl2yo8.us-east-2.rds.amazonaws.com:5432 ubuntu@18.224.51.91 -i /root/.ssh/id_rsa; done
        ports:
            - 5432:5432
        volumes:
            - ${PPK_FILE}:/root/.ssh/key.ppk:ro
        networks:
            - visitor-management
    ingress:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - visitor-management
networks:
    visitor-management: