version: "3.7"

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        build: .
        working_dir: /var/www
        command: sh -c "php vendor/bin/doctrine orm:schema-tool:update && php -S 0.0.0.0:8080 -t public"
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
        networks:
            - visitor-management
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_DB=navigate_5235
            - POSTGRES_USER=lauren
            - POSTGRES_PASSWORD=goFish49!zp9
            - POSTGRES_PORT=5434
            - ENV=dev
            - LOG_TARGET=/var/www/logs/app.log
            - REDIS_HOST=localhost
            - REDIS_PORT=5530
    postgres:
        image: postgres:12.1-alpine
        restart: "always"
        ports:
            - 5434
        environment:
            - POSTGRES_USER=lauren
            - POSTGRES_PASSWORD=goFish49!zp9
        networks:
            - visitor-management
networks:
    visitor-management:
