version: "3.7"

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: sh -c "php vendor/bin/doctrine orm:schema-tool:update && php -S 0.0.0.0:8080 -t public"
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - visitor-management
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_DB=visitor_management
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432
            - ENV=dev
            - LOG_TARGET=/var/www/logs/app.log
    postgres:
        image: postgres:12.1-alpine
        restart: "always"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        networks:
            - visitor-management
networks:
    visitor-management:
