{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "visitor-management-service.serviceAccountName" . }}
  labels:
{{ include "visitor-management-service.labels" . | nindent 4 }}
{{- end -}}
