replicaCount: 1

image:
  repository: 837238518041.dkr.ecr.us-east-2.amazonaws.com/vms/visitor-management-service
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: "LOG_TARGET"
    value: "php://stdout"
  - name: POSTGRES_HOST
    value: "test-innovations-v01.cm2dbdfl2yo8.us-east-2.rds.amazonaws.com"
  - name: POSTGRES_DB
    value: "navigate"
  - name: POSTGRES_USER
    value: "lauren"
  - name: POSTGRES_PASSWORD
    value: "goFish49!zp9"
  - name: POSTGRES_PORT
    value: "5432"
  - name: REDIS_HOST
    value: "test-redis.uooq9s.0001.use2.cache.amazonaws.com"
  - name: REDIS_PORT
    value: "6379"
  - name: AUTH_URL
    value: "https://test-auth.navigatep.com"
  - name: CLIENT_URL
    value:  a4ae7bc41cf9c419588963f4b3747e12-1612806275.us-east-2.elb.amazonaws.com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
